### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by catena2w** [coinbarn/coinbarn-extension#1]
- [x] Hide arrows in InputBlockMax (included in CSS directly for now)
- [x] Don't move input fields on error messages
- [ ] Too long ERG balance in header
- [x] Underscope is missed on tab switch on send screen 
- [x] No place for error message if transaction send failed for some reason
- [ ] Strange arror on dropdown on welcome back screen when clicked
- [ ] Fix issues with double multiplications
- [ ] Settings/About page
- [ ] Terms of use
- [ ] Publish to chrome store
